name: Build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare to build
    runs-on: ubuntu-latest
    steps:
      # Note: it returns 'release(=version tag)' and 'id(=version ID)'.
      - id: get-release-info
        name: Get release information
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: libvips
          repo: libvips
          excludes: prerelease, draft

      # Note: it returns 'exists(true or false)'.
      - id: check-duplicates
        name: Check duplicates
        uses: mukunku/tag-exists-action@v1.1.0
        with:
          tag: ${{steps.get-release-info.outputs.release}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      tag: ${{steps.get-release-info.outputs.release}}
      is-duplicated: ${{steps.check-duplicates.exists}}
  
  build:
    needs: prepare
    name: Build libvips
    runs-on: ubuntu-latest
    steps:    
      - id: checkout-libvips-builder
        name: Checkout libvips builder 
        uses: actions/checkout@v3
        with:
          repository: 'libvips/build-win64-mxe'
          
      - run: cd .. && sudo chmod 777 toybox-vips && cd toybox-vips
      
      - run: mkdir mxe && mkdir usr && sudo chmod 777 mxe && sudo chmod 777 usr
          
      - run: pwd && ls -al

      - id: build-amd64
        name: Build for AMD64
        run: ./build.sh --ref ${{needs.prepare.outputs.tag}} --with-hevc all x86_64 shared
      
      - id: build-armv7
        name: Build for ARMv7
        run: ./build.sh --ref ${{needs.prepare.outputs.tag}} --with-hevc all armv7 shared

      - run: ls -al
