name: Build libvips

on:
  workflow_call:
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare to build
    runs-on: ubuntu-latest
    steps:
      # Note: it returns 'release(=version tag)' and 'id(=version ID)'.
      - id: get-release-info
        name: Get release information
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: libvips
          repo: libvips
          excludes: prerelease, draft

      # Note: it returns 'exists(true or false)'.
      - id: check-duplicates
        name: Check duplicates
        uses: mukunku/tag-exists-action@v1.1.0
        with:
          tag: ${{steps.get-release-info.outputs.release}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build:
    needs: prepare
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run:  cd ~/ && pwd && ls -al
    
      - id: create-work-directory
        name: Create a work directory
        run: cd ~/ && mkdir workdir && sudo chmod 777 workdir && ls -al && cd workdir
    
      - id: checkout-libvips-builder
        name: Checkout libvips builder 
        uses: actions/checkout@v3
        with:
          repository: 'libvips/build-win64-mxe'
          
      - id: init-libvips-builder
        name: Initialize repository
        run: git init && git remote add origin https://github.com/libvips/build-win64-mxe.git

      - id: build-amd64
        name: Build for AMD64
        run: ./build.sh --with-hevc all x86_64 shared
      
      - id: build-armv7
        name: Build for ARMv7
        run: ./build.sh --with-hevc all armv7 shared

      - run: ls -al
