name: Check

on:
  schedule:
    # It runs every Monday.
    # Note: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-releases:
    name: Check releases
    runs-on: ubuntu-latest
    steps:
      # Note: it returns 'release(=version tag)' and 'id(=version ID)'.
      - id: get-release-info
        name: Get release information
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: libvips
          repo: build-win64-mxe
          excludes: prerelease, draft

      # Note: it returns 'exists(true or false)'.
      - id: check-duplicates
        name: Check duplicates
        uses: mukunku/tag-exists-action@v1.1.0
        with:
          tag: ${{steps.get-release-info.outputs.release}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      tag: ${{steps.get-release-info.outputs.release}}
      id: ${{steps.get-release-info.outputs.id}}
      is-duplicated: ${{steps.check-duplicates.exists}}
      
  call-workflows:
    needs: check-releases
    name: Call workflows
    runs-on: ubuntu-latest
    if: needs.check-releases.outputs.is-duplicated == false
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2
    
      - id: call-build-workflow
        name: Call build workflow
        uses: ./.github/workflows/build.yml
