name: Check

on:
  schedule:
    # It runs every Monday.
    # Note: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-releases:
    name: Check releases
    runs-on: ubuntu-latest
    steps:
      # Note: it returns 'release(=version tag)' and 'release_id(=version ID)'.
      - id: get-release-info
        name: Get release information
        uses: rez0n/actions-github-release@main
        env:
          repository: "libvips/build-win64-mxe"
          type: "stable"
          token: ${{ secrets.GITHUB_TOKEN }}

      # Note: it returns 'exists(true or false)'.
      - id: check-duplicates
        name: Check duplicates
        uses: mukunku/tag-exists-action@v1.1.0
        with:
          tag: ${{steps.get-release-info.outputs.release}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      tag: ${{steps.get-release-info.outputs.release}}
      id: ${{steps.get-release-info.outputs.release_id}}
      is-duplicated: ${{steps.check-duplicates.outputs.exists}}
      
  call-workflows:
    needs: check-releases
    name: Call workflows
    if: needs.check-releases.outputs.is-duplicated == 'false'
    uses: ./.github/workflows/build.yml
